# Netlify configuration: build + environment
# Sets stable Node.js to avoid runtime mismatches in CI.
# Dist output comes from scripts/build.mjs (esbuild) which writes to /dist.

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Use a stable LTS supported by Netlify builders.
  NODE_VERSION = "18.20.3"
  # Optional: avoid peer dependency resolution surprises on CI
  NPM_FLAGS = "--legacy-peer-deps"
